import { Inter } from 'next/font/google'
import '@/app/styles/globals.scss'
import Navbar from './layouts/navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='App'>
      <Navbar />
      {children}
      </body>
    </html>
  )
}
